### ISSUE TITLE
HidPnPWindowMixin not handle pnp events

### ISSUE THREAD

**Issue by filin86** [rene-aguirre/pywinusb#14]
when i try pnp_sample.py, script not handle any usb event (i.e. connect or disconnect).
python 3.3 x64, pywinusb 0.3.3, wxpython phoenix 3.0.1, pyqt 4.10, win 7 x64

script can find device on start but on_hid_pnp not calling after connect/disconnect devices

**Comment by rene-aguirre** [comment]
Fixed, tested with Python 2.7.9 x64, latest Windows patches, wxPython 3.0. Committed to PyPi version 0.3.5.
