### ISSUE TITLE
Inconsistency on buffer size ?

### ISSUE THREAD

**Issue by Overdrivr** [rene-aguirre/pywinusb#24]
When trying to send an 8 byte buffer, I get the following error:

```shell
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python34\lib\tkinter\__init__.py", line 1533, in __call__
    return self.func(*args)
  File "C:\Users\B48923\Documents\Testchip\04_Software\Client\GUI_Frames\Frame_manual.py", line 35, in send_frame
    self.model.send_frame(data,self.combobox.current())
  File "C:\Users\B48923\Documents\Testchip\04_Software\Client\Model.py", line 32, in send_frame
    self.usb_interface.send_frame(frame)
  File "C:\Users\B48923\Documents\Testchip\04_Software\Client\USB_HID_interface.py", line 49, in send_frame
    report[0].set_raw_data(buffer)
  File "C:\Python34\lib\site-packages\pywinusb\hid\core.py", line 1294, in set_raw_data
    % self.__raw_report_size )
pywinusb.hid.helpers.HIDError: Report size has to be 9 elements (bytes)
```

Why does the report is supposed to be 9 bytes ? I thought the standard was 8 bytes, such as indicated in ARM mbed cookbook :
https://developer.mbed.org/cookbook/USBHID-bindings-
Is there a way to change the report size ? Tried to search trough the code but couldn't find a simple way

EDIT :

I tried defining 9-bytes input and output reports microcontroller-side, and now pywinsub is requesting 10-bytes buffer data. I should have seen that coming. 
What's bothering me is that the received data microcontroller-side only contains 9 bytes (the first one being the report id), so one data byte lost somewhere in the process.

buffer to send (python side):
```shell
Buffer :[0, 218, 237, 0, 0, 0, 0, 0, 0, 0]
```

buffer received (micro side)
```shell
218 237 0 0 0 0 0 0 0 
```

First byte is lost.

**Comment by rene-aguirre** [comment]
The buffer sizes are affected by the HID report descriptors, can you confirm that in your firmware?

Input, output and feature reports can be described in a separate way, so might not match the size, as of usage schema.

Feel free to post information about your descriptors here.

**Comment by rene-aguirre** [comment]
Not a clear signal this is a library issue.
