### ISSUE TITLE
no dev found

### ISSUE THREAD

**Issue by hexxter** [rene-aguirre/pywinusb#34]
Hi,

i have WIN10 64bit  and this shows the devmanager:

HID\VID_040B&PID_6533&REV_0100
HID\VID_040B&PID_6533
HID\VID_040B&UP:0001_U:0005
HID_DEVICE_SYSTEM_GAME
HID_DEVICE_UP:0001_U:0005
HID_DEVICE

but if i use pywinusb 0.4.1 (python3.3) it found no device.
Is it problem with WIN10? 

My code:

import pywinusb.hid as hid

filter = hid.HidDeviceFilter()
all_devices = filter.get_devices()

if all_devices:
	print("Found %d matching hid devices" % len(all_devices))

More Info Dev:

    =========================== USB Port1 ===========================

Connection Status        : 0x01 (Device is connected)
Port Chain               : 1-1-1
Properties               : 0x01
 IsUserConnectable       : yes
 PortIsDebugCapable      : no
 PortHasMultiCompanions  : no

      ======================== USB Device ========================

        +++++++++++++++++ Device Information ++++++++++++++++++
Device Description       : USB-Eingabegerät
Device Path              : \\?\usb#vid_040b&pid_6533#6&24bfad55&0&1#{a5dcbf10-6530-11d2-901f-00c04fb951ed}
Device ID                : USB\VID_040B&PID_6533\6&24BFAD55&0&1
Driver KeyName           : {745a17a0-74d3-11d0-b6fe-00a0c90f57da}\0007 (GUID_DEVCLASS_HIDCLASS)
Driver                   : C:\WINDOWS\System32\drivers\hidusb.sys (Version: 10.0.10586.0  Date: 2015-10-30)
Driver Inf               : C:\WINDOWS\inf\input.inf
Legacy BusType           : PNPBus
Class                    : HIDClass
Service                  : HidUsb
Enumerator               : USB
Location Info            : Port_#0001.Hub_#0003
Location IDs             : PCIROOT(0)#PCI(1A00)#USBROOT(0)#USB(1)#USB(1), ACPI(_SB_)#ACPI(PCI0)#ACPI(EHC2)#ACPI(URTH)#ACPI(URMH)#ACPI(PRT8)
Container ID             : {36d9925a-0a46-11e6-98dd-f0def1de8935}
Manufacturer Info        : (Standardsystemgeräte)
Capabilities             : 0x84 (Removable, SurpriseRemovalOK)
Problem Code             : 0
Power State              : D3 (supported: D0, D1, D2, D3, wake from D0, wake from D1, wake from D2)
 Child Device 1          : HID-konformer Gamecontroller
  Device ID              : HID\VID_040B&PID_6533\7&1F774CD4&0&0000
  Class                  : HIDClass

        ---------------- Connection Information ---------------
Connection Index         : 0x01 (1)
Connection Status        : 0x01 (DeviceConnected)
Current Config Value     : 0x01
Device Address           : 0x02 (2)
Is Hub                   : 0x00 (no)
Number Of Open Pipes     : 0x01 (1)
Device Bus Speed         : 0x00 (Low-Speed)
Pipe0ScheduleOffset      : 0x00 (0)

        --------------- Connection Information V2 -------------
Connection Index         : 0x01 (1)
Length                   : 0x10 (16 bytes)
SupportedUsbProtocols    : 0x03
 Usb110                  : 1 (yes)
 Usb200                  : 1 (yes)
 Usb300                  : 0 (no)
 ReservedMBZ             : 0x00
Flags                    : 0x00
 DevIsOpAtSsOrHigher     : 0 (Is not operating at SuperSpeed or higher)
 DevIsSsCapOrHigher      : 0 (Is not SuperSpeed capable or higher)
 DevIsOpAtSsPlusOrHigher : 0 (Is not operating at SuperSpeedPlus or higher)
 DevIsSsPlusCapOrHigher  : 0 (Is not SuperSpeedPlus capable or higher)
 ReservedMBZ             : 0x00

        ------------------ Device Descriptor ------------------
bLength                  : 0x12 (18 bytes)
bDescriptorType          : 0x01 (Device Descriptor)
bcdUSB                   : 0x110 (USB Version 1.10)
bDeviceClass             : 0x00 (defined by the interface descriptors)
bDeviceSubClass          : 0x00
bDeviceProtocol          : 0x00
bMaxPacketSize0          : 0x08 (8 bytes)
idVendor                 : 0x040B (Weltrend Semiconductor)
idProduct                : 0x6533
bcdDevice                : 0x0100
iManufacturer            : 0x01 (String Descriptor 1)
 *!*ERROR String descriptor 1 not found
iProduct                 : 0x02 (String Descriptor 2)
 *!*ERROR String descriptor 2 not found
iSerialNumber            : 0x00 (No String Descriptor)
bNumConfigurations       : 0x01

      ---------------- Configuration Descriptor -----------------
bLength                  : 0x09 (9 bytes)
bDescriptorType          : 0x02 (Configuration Descriptor)
wTotalLength             : 0x0022 (34 bytes)
bNumInterfaces           : 0x01
bConfigurationValue      : 0x01
iConfiguration           : 0x00 (No String Descriptor)
bmAttributes             : 0xA0
 D7: Reserved, set 1     : 0x01
 D6: Self Powered        : 0x00 (no)
 D5: Remote Wakeup       : 0x01 (yes)
 D4..0: Reserved, set 0  : 0x00
MaxPower                 : 0x32 (100 mA)

        ---------------- Interface Descriptor -----------------
bLength                  : 0x09 (9 bytes)
bDescriptorType          : 0x04 (Interface Descriptor)
bInterfaceNumber         : 0x00
bAlternateSetting        : 0x00
bNumEndpoints            : 0x01 (1 Endpoint)
bInterfaceClass          : 0x03 (HID - Human Interface Device)
bInterfaceSubClass       : 0x00 (None)
bInterfaceProtocol       : 0x00 (None)
iInterface               : 0x00 (No String Descriptor)

        ------------------- HID Descriptor --------------------
bLength                  : 0x09 (9 bytes)
bDescriptorType          : 0x21 (HID Descriptor)
bcdHID                   : 0x0100 (HID Version 1.00)
bCountryCode             : 0x00 (00 = not localized)
bNumDescriptors          : 0x01
Descriptor 1:
bDescriptorType          : 0x22 (Class=Report)
wDescriptorLength        : 0x0033 (51 bytes)
Error reading descriptor : ERROR_GEN_FAILURE

        ----------------- Endpoint Descriptor -----------------
bLength                  : 0x07 (7 bytes)
bDescriptorType          : 0x05 (Endpoint Descriptor)
bEndpointAddress         : 0x81 (Direction=IN EndpointID=1)
bmAttributes             : 0x03 (TransferType=Interrupt)
wMaxPacketSize           : 0x0008
bInterval                : 0x0A (10 ms)

**Comment by rene-aguirre** [comment]
@hexxter, HID_DEVICE_SYSTEM_GAME shows your device is protected by Windows, this is a limitation on this library, it just works because it just uses Windows HID application class services, no drivers are required.

If you still need low level access to your device you'd need to use a library that install a USB filter driver.

Otherwise just check what API services could be used to use your device.
