### ISSUE TITLE
How to determine if the device is opened!

### ISSUE THREAD

**Issue by zhangshengping** [rene-aguirre/pywinusb#40]
I use the code below to get a HID device. But I don't whether the device is opened or closed. 
I try to use `HIDDevice.is_opened()` to get the status, but it throw a error `SyntaxError: invalid syntax`.
What should I do to get the status of the HID device?
```python

filter = hid.HidDeviceFilter()
all_devices = filter.get_devices()
HIDDevice = all_devices[0]
```

**Comment by rene-aguirre** [comment]
HIDDevice matches a pyWinUsb class name.

Please refer to the intro in the wiki and review the examples.
