### ISSUE TITLE
Typo in formated output

### ISSUE THREAD

**Issue by PixelPartner** [rene-aguirre/pywinusb#48]
https://github.com/rene-aguirre/pywinusb/blob/c625c9d0b04b629e73be04cb2ebfdfc26965fac5/pywinusb/hid/tools.py#L46

It shoud read `Product String:` instead of `Product Sting: `

**Comment by rene-aguirre** [comment]
Thanks @PixelPartner !

**Comment by mcuee** [comment]
Probably this can be fixed in a new commit.

**Comment by rene-aguirre** [comment]
done, thanks!
