### ISSUE TITLE
Can the raw_data read a HID-compitable mouse deivce ?

### ISSUE THREAD

**Issue by glucee** [rene-aguirre/pywinusb#49]
I run the raw_data code, and it can recognise several devices (they are keyboard or touchpad), when I select anyone, none of them returns raw data. Is it the limitation of the pywinusb ? Or how can I get the raw data from the touchpad or similar device ? Thanks.

**Comment by mcuee** [comment]
I think not if they are using different driver/API. pywinusb is for generic HID device, not for keyboard/mouse.

**Comment by rene-aguirre** [comment]
Hello @glucee , that's actually a Windows OS restriction, HID input (keyboards, mice, some game devices) are restricted to direct application access as there are other system specific ways of dealing with those.

**Comment by takeraparterer** [comment]
hi, @rene-aguirre I also had this problem, what are those ways?

**Comment by takeraparterer** [comment]
hi, @rene-aguirre I also had this problem, what are those ways?

**Comment by mcuee** [comment]
One possibility: Raw Input
https://learn.microsoft.com/en-us/windows/win32/inputdev/raw-input
