### ISSUE TITLE
hid.core.show_hids() fails under Python 2 if there is a Unicode character in the device name

### ISSUE THREAD

**Issue by BoarGules** [rene-aguirre/pywinusb#55]
Under Python 2, this 

```
    if all_hids:
        print("Found HID class devices!, writting details...")
        for dev in all_hids:
            device_name = str(dev)
```
fails because `str()` attempts to do an implicit ascii conversion and fails. So even though the calls to `output.write()` will work correctly if there is non-ascii encoding in the data they report, the code never gets to the point of calling them if there is non-ascii encoding in the device name.

In my case the device name in question is *Natural® Ergonomic Keyboard 4000*.

This is only an issue under Python 2. The corresponding `str()` call in Python 3 does the right thing.

**Comment by rene-aguirre** [comment]
This is Python limitation. You need to manage your encoding.

Check the `show_hids.py` example, run it first it might have already what you need. It if doesn't work try customizing the target codecs that are suitable for your device encoding (it case of not following utf8)
