### ISSUE TITLE
cx_Freeze can't find module pywinusb

### ISSUE THREAD

**Issue by JulienCochuyt** [rene-aguirre/pywinusb#61]
When trying to cx_Freeze an app using pywinusb 0.4.2 installed with pip, the build fails unable for find module pywinusb.
As described [here](https://sourceforge.net/p/cx-freeze/mailman/message/30998577/), it appears that __init__.py is missing from the installed root package.

Manually- adding an empty __init__.py to Lib/site-packages/pywinusb/ solves the issue and cx_Freeze builds just fine.

**Comment by rene-aguirre** [comment]
Try with `pywinusb.hid` not `pywinusb`. That's the only package namespace implemented.

**Comment by JulienCochuyt** [comment]
@rene-aguirre, thanks for the quick reply.
> Try with `pywinusb.hid` not `pywinusb`. That's the only package namespace implemented.

My bad.
Adding `pywinusb.hid` to the package list does not help as cx_Freeze tries (and fails) to walk up the package tree.
However cx_Freeze 4.3.2 added a `namespace_packages` option list which accepts `pywinusb` just fine.
