### ISSUE TITLE
Not reading mouse usb 

### ISSUE THREAD

**Issue by movie99** [rene-aguirre/pywinusb#62]
Thank you for the amazing library, when Using  the library its able to detect every device except the mouse I really don’t know why. I was hoping to create something like this but for windows  >(https://www.orangecoat.com/how-to/read-and-decode-data-from-your-mouse-using-this-pyusb-hack) also was wondering if you could help me out

**Comment by rene-aguirre** [comment]
Sorry, that's a limitation. Mice and Keyboards are system input devices you need a kernel driver helper, pyusb and others implement USB filters that allow to capture any device.

The `pywinusb` uses only application level APIs, which restrict access to system devices.

So it is not supported.
