### ISSUE TITLE
Can't see all the HID devices connected to the PC

### ISSUE THREAD

**Issue by hiteshkhanna31** [rene-aguirre/pywinusb#70]
I am trying to read STM32F3 as USB HID Keyboard but when run the show_hid.py  file  it does not show all th HID connected to the PC. I tried to give the vendor id and product id as well but i get the output on console as below:

> There's not any non system HID class device available

**Comment by rene-aguirre** [comment]
That's a known Windows limitation.

`PyWinUsb` only uses Application level APIs, system devices low level access requires a system driver, which is not in the scope of this library.

try `libusb`, once you install a usb filter driver you'll be able to access any usb device.
